# Generated by Django 3.2.13 on 2022-07-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("child_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childwebsitesessionid",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="sites.site"
            ),
        ),
    ]
