# Generated by Django 3.2.13 on 2022-08-03 13:10

import child_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("child_auth", "0003_telegramchat"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramchat",
            name="user_friendly_name",
            field=models.CharField(
                default=child_auth.models.generate_chat_name, max_length=50, unique=True
            ),
        ),
    ]
