# Generated by Django 3.2.13 on 2022-08-08 10:50

import allauth_providers.discord.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("socialaccount", "0003_extra_data_default_dict"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordBotInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.BigIntegerField()),
                (
                    "user_friendly_name",
                    models.CharField(
                        default=allauth_providers.discord.models.generate_chat_name,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        help_text="This field defines maps to the SocialAccount of the user who added the Bot to the guild",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socialaccount.socialaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuildRoleMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=100)),
                ("role_id", models.BigIntegerField()),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discord.discordbotinstallation",
                    ),
                ),
            ],
            options={
                "unique_together": {("role_id", "guild")},
            },
        ),
    ]
