# Generated by Django 4.0.4 on 2022-06-15 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="name of the FPM package", max_length=255, unique=True
                    ),
                ),
                (
                    "git",
                    models.CharField(
                        help_text="git url of FPM package", max_length=1023
                    ),
                ),
                (
                    "hash",
                    models.CharField(
                        blank=True,
                        help_text="latest deployed hash of git",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        help_text="We have different plans like free, paid for serving FPM package",
                        max_length=255,
                    ),
                ),
                ("hours", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("deployed", "Package Deployed"),
                            ("in_dev", "In development state"),
                        ],
                        help_text="status of the package",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DedicatedInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ec2_reservation", models.CharField(db_index=True, max_length=255)),
                (
                    "ec2_instance_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initializing", "Instance Initializing"),
                            ("ready", "Instance ready to serve"),
                            ("failed", "Failed to initialize"),
                        ],
                        help_text="status of EC2 instance, ready, initializing, ect...",
                        max_length=127,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fpm.package"
                    ),
                ),
            ],
        ),
    ]
