# Generated by Django 4.0.4 on 2022-06-14 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='name of the FPM package', unique=True)),
                ('git', models.TextField(help_text='git url of FPM package')),
                ('hash', models.TextField(blank=True, help_text='latest deployed hash of git', null=True)),
                ('plan', models.TextField(help_text='We have different plans like free, paid for serving FPM package')),
                ('hours', models.IntegerField(default=0)),
                ('status', models.TextField(help_text='status of the package')),
            ],
        ),
        migrations.CreateModel(
            name='DedicatedInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec2_reservation', models.TextField(db_index=True)),
                ('ec2_instance_id', models.TextField(blank=True, null=True)),
                ('status', models.TextField(help_text='status of EC2 instance, ready, initializing, ect...')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpm.package')),
            ],
        ),
    ]
