# Generated by Django 4.0.4 on 2022-06-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0002_packagedomainmap_plan_remove_package_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dedicatedinstance',
            name='ec2_reservation',
        ),
        migrations.AlterField(
            model_name='dedicatedinstance',
            name='ec2_instance_id',
            field=models.CharField(db_index=True, default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
