# Generated by Django 3.2.13 on 2022-06-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0003_remove_dedicatedinstance_ec2_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedicatedinstance',
            name='config',
            field=models.FileField(blank=True, null=True, upload_to='confs'),
        ),
        migrations.AlterField(
            model_name='dedicatedinstance',
            name='status',
            field=models.CharField(choices=[('INITIALIZING', 'Initializing'), ('READY', 'Ready'), ('STOPPED', 'Stopped')], help_text='status of EC2 instance, ready, initializing, ect...', max_length=127),
        ),
    ]
