# Generated by Django 3.2.13 on 2022-07-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fpm", "0010_auto_20220725_1530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="app_secret",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
