# Generated by Django 3.2.13 on 2022-07-27 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ("sites", "0002_alter_domain_unique"),
        ("fpm", "0011_alter_package_app_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="app_secret",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="package",
            name="application",
            field=models.OneToOneField(
                default=6,
                on_delete=django.db.models.deletion.PROTECT,
                to="oauth2_provider.application",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="package",
            name="site",
            field=models.OneToOneField(
                default=4, on_delete=django.db.models.deletion.PROTECT, to="sites.site"
            ),
            preserve_default=False,
        ),
    ]
